{{- $saltApiIngress := .Values.ingress.saltApi -}}

{{- if $saltApiIngress.enabled -}}
{{- $ingressPath := $saltApiIngress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-salt-api
  labels:
    app: {{ include "salt-master.name" . }}
    chart: {{ include "salt-master.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with $saltApiIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $saltApiIngress.tls }}
  tls:
  {{- range $saltApiIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $saltApiIngress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $.Release.Name }}-salt-api
              servicePort: http
  {{- end }}
{{- end }}
